version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - flask-app
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  mysql:
    image: liocaman/trio-db
    build: ./db
    ports: 
    - target: 3306
      published: 3306 
      protocol: tcp
    environment:
      MYSQL_ROOT_PASSWORD: ${password}
      MYSQL_DATABASE: flask-db  
  flask-app: 
    image: liocaman/trio-app
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
    depends_on: 
    - mysql
    
