version: 3.7
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  mysql:
    build: ./db
    ports: 
    - target: 3306
      published: 3306 
      protocol: tcp
  flask-app: 
    build: ./flask-app
    ports:
    - target: 5000
      publishd: 5000
      protocol: tcp

    
