version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - flask-app
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  mysql:
    build: ./db
    ports: 
    - target: 3306
      published: 3306 
      protocol: tcp
    environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=flask-db  
  flask-app: 
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
    - SECRET_KEY=thisismysecretkey
    depends_on: 
    - mysql
    
